#pragma once
#include "base/ccConfig.h"

#include "cocos/scripting/js-bindings/jswrapper/SeApi.h"

extern se::Object* __jsb_PluginProxyWrapper_proto;
extern se::Class* __jsb_PluginProxyWrapper_class;

bool js_register_PluginProxyWrapper(se::Object* obj);
bool register_all_cocos2dx_PluginProxyWrapper(se::Object* obj);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_showAds);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_StartPhoneVibrate);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_voiceOver);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_getIsPushOn);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_setStatusBarIsHidden);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_switchPluginXRunEnv);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_setPackageName);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_getSystemContactInfos);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_getBatteryLevel);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_copyToClipboard);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_jump2ExtendMethod);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_getSDKVersion);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_loadImageFinished);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_setIapCallBack);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_getMacAddress);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_getDeviceIMEI);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_setPluginConfig);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_PluginLog);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_getDeviceName);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_getPluginVersion);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_SystemShare);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_getDeviceIMSI);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_getStatusBarHeight);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_getSocialURLParams);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_getSimType);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_stopSound);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_getReachability);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_getWIFILevel);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_getVersionCode);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_getVersionName);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_voiceStart);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_sendSMS);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_openURL);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_hideAds);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_userItemsLogin);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_payForProduct);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_startUpdatingLocation);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_getPackageName);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_getDeviceType);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_getClipBoardContent);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_voiceWantToCancel);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_logEvent);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_openGPS);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_logout);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_playSound);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_loadPlugin);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_setSessionCallBack);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_StartPushSDKItem);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_initHeadFace);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_pushToUser);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_setSocialCallBack);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_clearSocialURLParams);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_setAdsCallBack);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_openPush);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_callPhone);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_getCurrentNetDBM);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_shareWithItems);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_exitApp);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_setPlatformCallBack);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_getInstance);
SE_DECLARE_FUNC(js_cocos2dx_PluginProxyWrapper_PluginProxyWrapper_PluginProxyWrapper);

